apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics-datasource
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm-k8s.monitoring.svc:8429
    isDefault: true
    jsonData:
      httpMethod: POST
