apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: monitoring
  labels:
    dashboards: "grafana"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: admin
      admin_password: prom-operator
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-srzlab-tech
    spec:
      ingressClassName: external-ingress
      rules:
        - host: grafana.srzlab.tech
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: grafana-instance-service
                    port:
                      number: 3000
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.srzlab.tech
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:13.1.0
