# Helm values configuration overriding the Grafana sub-chart settings
# Ref: https://github.com/grafana/helm-charts/tree/main/charts/grafana

grafana:
  image:
    repository: grafana/grafana
    tag: "10.4.1" # Pinned image version
    pullPolicy: IfNotPresent

  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  admin:
    existingSecret: "grafana-admin-credentials"
    userKey: admin-user
    passwordKey: admin-password

  ingress:
    enabled: true
    ingressClassName: "external-ingress"
    hosts:
      - grafana.srzlab.tech
    path: /
