# Helm values configuration overriding the ingress-nginx sub-chart settings
# Ref: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

ingress-nginx:
  controller:
    ingressClassResource:
      name: "external-ingress"
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-external"
    ingressClass: "external-ingress"
    service:
      type: LoadBalancer
      loadBalancerIP: "34.101.112.48"


