apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaldyrz/devops-homework.git'
    targetRevision: HEAD
    path: deploy/gateway
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
