# Helm values configuration for ArgoCD (argo-cd chart)

server:
  extraArgs:
    - --insecure
  
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    ingressClassName: "external-ingress"
    hostname: "argocd.srzlab.tech"
    path: /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-srzlab-tech"
    tls: true

configs:
  params:
    server.insecure: "true"
