# Helm values configuration for ArgoCD (argo-cd chart)

server:
  extraArgs:
    - --insecure
  
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    ingressClassName: "external-ingress"
    hosts:
      - argocd.srzlab.tech
    paths:
      - /

configs:
  params:
    server.insecure: "true"
