# Standalone kube-state-metrics configuration
# Ref: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics

kube-state-metrics:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: kube-state-metrics
