apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: asia-southeast2-docker.pkg.dev/ambient-stone-281407/interopera/rag-api
  newName: asia-southeast2-docker.pkg.dev/ambient-stone-281407/interopera/rag-api
  newTag: 5525a66
